{{- /*
Deploy the DAQ receivers. For example:

receivers:
  1:
    storage: daq-data
    node_selector:
      kubernetes.io/hostname: psi-node3
    runtime_class: nvidia
    gpu_limit: "1"
    grpc_port: 50052  # optional; defaults to 50051
    data_port: 4661  # optional; defaults to 4660

*/}}
{{- $image := .Values.image}}
{{- range $name, $spec := .Values.receivers}}
{{- $slug := (printf "daq-receiver-%s" $name)}}
{{- $grpc_port := default 50051 $spec.port}}
{{- $data_port := default 4660 $spec.data_port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}
  labels:
    component: {{$slug}}
spec:
  ports:
  - name: {{$slug}}-grpc-port
    port: {{$grpc_port}}
    protocol: TCP
  selector:
    component: {{$slug}}-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}-data
  labels:
    component: {{$slug}}
spec:
  ports:
  - name: {{$slug}}-data-port
    port: {{$data_port}}
    protocol: UDP
  selector:
    component: {{$slug}}-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$slug}}-server
  labels:
    component: {{$slug}}-server
spec:
  selector:
    matchLabels:
      component: {{$slug}}-server
  serviceName: {{$slug}}
  replicas: 1
  template:
    metadata:
{{- with $spec.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        component: {{$slug}}-server
    spec:
{{- with $spec.runtime_class}}
      runtimeClassName: {{quote .}}
{{- end }}
      containers:
      - command:
        - MccsDaqServer
        name: {{$slug}}-server
{{- with $image}}
        image: {{.registry}}/{{.name}}:{{.tag | default $.Chart.AppVersion}}
{{- end }}
        imagePullPolicy: IfNotPresent
        env:
          - name: DAQ_GRPC_PORT
            value: {{$grpc_port | quote}}
        ports:
          - containerPort: {{$grpc_port}}
            protocol: TCP
{{- with $spec.gpu_limit}}
        resources:
          limits:
            nvidia.com/gpu: {{quote .}}
{{- end }}
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - IPC_LOCK
            - SYS_NICE
            - SYS_ADMIN
            - KILL
            - SYS_TIME
{{- with $spec.storage}}
        volumeMounts:
        - name: {{.}}
          mountPath: /product # ADR-55 requires this name
      volumes:
      - name: {{.}}
        persistentVolumeClaim:
          claimName: {{.}}
      securityContext:
        fsGroup: 1000
{{- end }}
{{- with $spec.node_selector}}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $spec.affinity}}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $spec.tolerations}}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
