{{- /*
Deploy the DAQ receivers. For example:

receivers:
  ci-1-bandpass:
    grpc_port: 50051
    receiver_interface: net1
    receiver_ip: 10.0.0.1
    receiver_port: 4660
    nvidia_gpu: true
    storage: daq-data
    expose_data_service: true # optional: defaults to false
    node_selector:
      kubernetes.io/hostname: psi-node3

*/}}
{{- $image := .Values.image}}
{{- range $name, $spec := .Values.receivers}}
{{- $slug := (printf "daqrx-%s" $name)}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}
  labels:
    component: {{$slug}}
spec:
  ports:
  - name: {{$slug}}-grpc-port
    port: {{$spec.grpc_port}}
    protocol: TCP
  selector:
    component: {{$slug}}-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}-data
  labels:
    component: {{$slug}}
spec:
{{- if $spec.expose_data_service}}
  type: LoadBalancer
{{- end}}
  ports:
  - name: {{$slug}}-data-port
    port: {{$spec.receiver_port}}
    protocol: UDP
  selector:
    component: {{$slug}}-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$slug}}-server
  labels:
    component: {{$slug}}-server
spec:
  selector:
    matchLabels:
      component: {{$slug}}-server
  serviceName: {{$slug}}
  replicas: 1
  template:
    metadata:
{{- with $spec.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        component: {{$slug}}-server
    spec:
{{- if $spec.nvidia_gpu}}
      runtimeClassName: nvidia
{{- end }}
      containers:
      - command:
        - MccsDaqServer
        name: {{$slug}}-server
{{- with $image}}
        image: {{.registry}}/{{.name}}:{{.tag | default $.Chart.AppVersion}}
{{- end }}
        imagePullPolicy: IfNotPresent
        env:
          - name: DAQ_GRPC_PORT
            value: {{$spec.grpc_port | quote}}
          - name: DAQ_RECEIVER_INTERFACE
            value: {{$spec.receiver_interface | quote}}
          - name: DAQ_RECEIVER_IP
            value: {{get $spec "receiver_ip" | default "" | quote}}
          - name: DAQ_RECEIVER_PORTS
            value: {{$spec.receiver_port | quote}}
        ports:
          - containerPort: {{$spec.grpc_port}}
            protocol: TCP
{{- if $spec.nvidia_gpu}}
        resources:
          limits:
            nvidia.com/gpu: 1
{{- end }}
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - IPC_LOCK
            - SYS_NICE
            - SYS_ADMIN
            - KILL
            - SYS_TIME
        volumeMounts:
        - name: daq-mount
          mountPath: /product # ADR-55 requires this name
      volumes:
      - name: daq-mount
{{- if hasKey $spec "storage"}}
        persistentVolumeClaim:
          claimName: {{$spec.storage}}
{{- else}}
        emptyDir:
          medium: Memory
{{- end }}
      securityContext:
        fsGroup: 1000
{{- with $spec.node_selector}}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $spec.affinity}}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $spec.tolerations}}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
