{{- /*
Launch a managed DAQ receiver.

For each receiver spec, check if it has a "grpc_ip" key.
If not, then we need to launch a receiver instance.
*/}}
{{- $image := .Values.image}}
{{- range $id, $spec := .Values.receivers}}
{{- if not (hasKey $spec "external_ip") }}
{{- $slug := (printf "daq-receiver-%03d" (int $id))}}
{{- $grpc_port := default 50051 $spec.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}
  namespace: dp-mccs-alistair-p
  labels:
    component: {{$slug}}
spec:
  ports:
  - name: {{$slug}}-grpc-port
    port: {{$grpc_port}}
    protocol: TCP
  selector:
    component: {{$slug}}-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$slug}}-server
  namespace: dp-mccs-alistair-p
  labels:
    component: {{$slug}}-server
spec:
  selector:
    matchLabels:
      component: {{$slug}}-server
  serviceName: {{$slug}}
  replicas: 1
  template:
    metadata:
{{- with $spec.server_annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        component: {{$slug}}-server
    spec:
      runtimeClassName: nvidia
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      containers:
      - args:
        - trap exit TERM INT; sleep infinity & wait
        command:
        #- MccsDaqServer
        - /bin/bash
        - -c
        - --
        name: {{$slug}}-server
{{- with $image}}
        image: {{.registry}}/{{.name}}:{{.tag}}
{{- end }}
        imagePullPolicy: IfNotPresent
        # command:
        #   - MccsDaqServer
        env:
          - name: DAQ_GRPC_PORT
            value: {{$grpc_port | quote}}
        ports:
          - containerPort: {{$grpc_port}}
            protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - IPC_LOCK
            - SYS_NICE
            - SYS_ADMIN
            - KILL
            - SYS_TIME
{{- with $spec.storage}}
        volumeMounts:
        - name: {{.}}
          mountPath: /daq-data
      volumes:
      - name: {{.}}
        persistentVolumeClaim:
          claimName: {{.}}
      securityContext:
        fsGroup: 1000
{{- end }}
{{- with $spec.server_node_selector}}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $spec.server_affinity}}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
# {{- with $spec.server_tolerations}}
#       tolerations:
# {{ toYaml . | indent 8 }}
#{{- end }}
{{- end }}
{{- end }}
