{{ $localchart := . }}
{{- range $key, $device := .Values.deviceServers.daqreceiver.devices }}
---
{{- $context := dict "name" $device.name "device" $device "local" $localchart}}
{{- if eq (default "internal" $device.grpc_host_type) "external" }}
{{ template "ska-low-mccs-daq.daq-server-external.tpl" $context }}
{{- else }}
{{ template "ska-low-mccs-daq.daq-server-internal.tpl" $context }}
{{- end }}
{{- end }}