{{- /*
Launch a DAQ tango device.

For each receiver spec, generate a ska-tango-util multidevice spec
by pushing the current context through the DAQ spec template.
Then convert that spec into k8s manifests by pushing it through
the ska-tango-util library functions.
*/}}
{{- $filedeviceserver := tpl ($.Files.Get "data/daq.yaml") $ | fromYaml }}
{{- $context := dict
  "name" "daq"
  "deviceserver" $filedeviceserver
  "image" .Values.image
  "local" .
}}
{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }}
