{{- /*
Create egress to pre-existing DAQ receivers provided by the platform.
For example,

receiver_egresses:
  1:
    ip: 10.80.81.82
    port: 50052  # optional; defaults to 50051

*/}}
{{- range $id, $spec := .Values.receiver_egresses}}
{{- $service_name := (printf "daq-receiver-%03d" (int $id))}}
{{- $port := default 50051 $spec.port}}
---
kind: Endpoints
apiVersion: v1
metadata:
 name: {{$service_name}}
subsets:
 - addresses:
     - ip: {{$spec.ip}}
   ports:
     - port: {{$port}}
---
kind: Service
apiVersion: v1
metadata:
 name: {{$service_name}}
spec:
 type: ClusterIP
 ports:
 - port: {{$port}}
   targetPort: {{$port}}
{{- end }}
