{{ $localchart := . }}
{{- range $key, $device := .Values.deviceServers.daqreceiver.devices }}
---
{{- $context := dict "name" $device.name "device" $device "local" $localchart}}
{{- if hasKey $device "grpc_ip" }}
{{ template "ska-low-mccs-daq.daq-server-external.tpl" $context }}
{{- else }}
{{ template "ska-low-mccs-daq.daq-server-internal.tpl" $context }}
{{- end }}
{{- end }}