{{- /*
Launch a managed DAQ receiver.

For each receiver spec, check if it has a "grpc_ip" key.
If not, then we need to launch a receiver instance.
*/}}
{{- $image := .Values.image}}
{{- with .Values.receiver}}
{{- if not (hasKey . "external_ip") }}
{{- $slug := (printf "daq-receiver-%03d" (int .station_id))}}
{{- $grpc_port := default 50051 $.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$slug}}
  labels:
    component: {{$slug}}
spec:
  ports:
  - name: {{$slug}}-grpc-port
    port: {{$grpc_port}}
    protocol: TCP
  selector:
    component: {{$slug}}-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$slug}}-server
  labels:
    component: {{$slug}}-server
spec:
  selector:
    matchLabels:
      component: {{$slug}}-server
  serviceName: {{$slug}}
  replicas: 1
  template:
    metadata:
{{- with .server_annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        component: {{$slug}}-server
    spec:
      containers:
      - name: {{$slug}}-server
{{- with $image}}
        image: {{.registry}}/{{.name}}:{{.tag}}
{{- end }}
        imagePullPolicy: IfNotPresent
        command:
          - retry
          - --max=60
          - --
          - MccsDaqServer
        ports:
          - containerPort: {{$grpc_port}}
            protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - IPC_LOCK
            - SYS_NICE
            - SYS_ADMIN
            - KILL
            - SYS_TIME
{{- with .storage }}
        volumeMounts:
        - name: {{.}}
          mountPath: /daq-data
      volumes:
      - name: {{.}}
        persistentVolumeClaim:
          claimName: {{.}}
      securityContext:
        fsGroup: 1000
{{- end }}
{{- with .server_node_selector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .server_affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .server_tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
