apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-runner
  namespace: ska-low-mccs-daq
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: k8s-test-runner
    image: artefact.skao.int/ska-low-mccs-daq-test-runner:0.1.2
    imagePullPolicy: IfNotPresent
    command: [ "sleep", "infinity" ]
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-test:10000
