# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdaq.proto\")\n\x0fstartDaqRequest\x12\x16\n\x0emodes_to_start\x18\x01 \x01(\t\"\x10\n\x0estopDaqRequest\"D\n\x0f\x63ommandResponse\x12 \n\x0bresult_code\x18\x01 \x01(\x0e\x32\x0b.ResultCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x10\x63onfigDaqRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"\x10\n\x0enoParamRequest*r\n\nResultCode\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\n\n\x06QUEUED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\x12\x0c\n\x08REJECTED\x10\x05\x12\x0f\n\x0bNOT_ALLOWED\x10\x06\x12\x0b\n\x07\x41\x42ORTED\x10\x07\x32\xce\x01\n\x03\x44\x61q\x12\x30\n\x08StartDaq\x12\x10.startDaqRequest\x1a\x10.commandResponse\"\x00\x12.\n\x07StopDaq\x12\x0f.stopDaqRequest\x1a\x10.commandResponse\"\x00\x12.\n\x07InitDaq\x12\x0f.noParamRequest\x1a\x10.commandResponse\"\x00\x12\x35\n\x0c\x43onfigureDaq\x12\x11.configDaqRequest\x1a\x10.commandResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULTCODE._serialized_start=198
  _RESULTCODE._serialized_end=312
  _STARTDAQREQUEST._serialized_start=13
  _STARTDAQREQUEST._serialized_end=54
  _STOPDAQREQUEST._serialized_start=56
  _STOPDAQREQUEST._serialized_end=72
  _COMMANDRESPONSE._serialized_start=74
  _COMMANDRESPONSE._serialized_end=142
  _CONFIGDAQREQUEST._serialized_start=144
  _CONFIGDAQREQUEST._serialized_end=178
  _NOPARAMREQUEST._serialized_start=180
  _NOPARAMREQUEST._serialized_end=196
  _DAQ._serialized_start=315
  _DAQ._serialized_end=521
# @@protoc_insertion_point(module_scope)
