apiVersion: v2
description: A Helm chart for deploying monitoring and control of the DAQ receiver.
name: ska-low-mccs-daq-lmc
version: 0.3.0
appVersion: 0.3.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-tango-util
    version: 0.3.23
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.3.10
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
