#This deployment is aimed at oxford.
#This is a temporary file for performing the demo in MCCS-1203
#We want the following deployment:
# - TPM (x1)
# - DAQ (x1)
# - Subrack (simulated x1)
# - Jupyter Notebook
jupyterhub:
  hub:
    baseUrl: /jupyterhub/
  ingress:
    pathType: Prefix
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  singleuser:
    image:
      name: registry.gitlab.com/ska-telescope/sdi/ska-cicd-deploy-low-itf/tango-notebook
      tag: 0.1.1
    extraEnv:
      TANGO_HOST: "databaseds-tango-base-test.ska-low-mccs-daq:10000"
  proxy:
    service:
      type: ClusterIP

#Dissable all the TPMs except the one of interest.
#From spshw we want a TPM and a Subrack simulator
ska-low-mccs-spshw:
  facility: oxford 
  ska-tango-base:
    enabled: false
  simulators:
    subracks:
      1:
        host: subrack-simulator-1
  deviceServers:
    tpms:
      instances:
        1:
          enabled: false
        2:
          enabled: false
        3:
          host: 10.0.10.5 #Not needed as default (it is good practice to ensure this way?)
          enabled: true
        4:
          enabled: false
      logging_level_default: 5
      resources:
        requests:
          memory: 512Mi

# From DAQ we want a single DAQ instance
# For this demo we are building a daq image meaning we do not 
# need a new release
ska-low-mccs-daq:
  ska-tango-base:
    enabled: false
  low_mccs_daq:
    enabled: true
    image:
      registry: artefact.skao.int
      image: ska-low-mccs-daq
      tag: 0.2.0 #VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
      pullPolicy: IfNotPresent
  securityContext:
    capabilities:
      add: ["NET_RAW", "IPC_LOCK", "SYS_NICE", "SYS_ADMIN", "KILL", "SYS_TIME"]
  deviceServers:
    daqreceiver:
      file: "data/daq-receiver.yaml"
      devices:
        - name: daqreceiver-001
          device_name: low-mccs-daq/daqreceiver/001  # mandatory
          daq_id: 1  # optional: defaults to position in this list
          #This interface should be the 40G interface at the site of deployment.
          receiver_interface: enp34s0  # currently this has to be adjusted per site interfaces 
          receiver_ip: ""  # This can be worked out from the receiver interface
          receiver_port: 4660  # port on the receiver interface to listen for udp spead packets
          # This is the IP:PORT for the gRPC to form its TCP connection.
          grpc_host_type: "internal"
          grpc_ip: "10.2.2.184" 
          grpc_port: 50051
          
