platform:
  array:
    stations:
      ci-1:
        id: 1
        sps: {}

platform:
  stations:
    ci-1:
      sps:
        daq:
          two-pod-daq: false
    real-daq-1:
      sps:
        daq:
          two-pod-daq: false

helm_values:
  ska-tango-devices:
    devices:
      MccsDaqReceiver:
        low-mccs/daqreceiver/real-daq-1:
          NumberOfTiles: 8
        low-mccs/daqreceiver/real-daq-1-bandpass:
          NumberOfTiles: 8