platform:
  array:
    stations:
      ci-1:
        id: 1
        sps: {}
  stations:
    ci-1:
      sps:
        daq:
          two-pod-daq: false
    real-daq-1:
      sps:
        daq:
          two-pod-daq: false

# helm_values:
#   ska-tango-devices:
#     deviceServerTypes:
#       daq:
#         image:
#           registry: docker.io/library
#           tag: 3.0.0-rc2-dirty