environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/stfc-ci.yaml
      - values/values-stfc-ci.yaml
  aa0.5-production:
    kubeContext: infra:au-aa-mccs-cloud01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=6e3a54c5487a1f4abdc5a4be13a219b0816df1e7
      - values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=dfb6c074539d1215562f8cc0f20245b0dbd8c2de
  aavs3-staging:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=dfb6c074539d1215562f8cc0f20245b0dbd8c2de
      - values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=dfb6c074539d1215562f8cc0f20245b0dbd8c2de
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=1b0c5906a2a92a481a507d916b568295be52d4bb
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=1b0c5906a2a92a481a507d916b568295be52d4bb
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c42bc5d97267a3c6e04f9ab412b0d03e947a6d4e
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c42bc5d97267a3c6e04f9ab412b0d03e947a6d4e
      - platform/minikube.yaml
  stfc-ral:
    values:
      - platform/stfc-ral.yaml
      - values/values-stfc-ral.yaml
  
---

repositories: []

releases:
  - name: ska-low-mccs-daq
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-daq
    version: 0.6.2
    values:
      - templates/daq.yaml.gotmpl
      - templates/helm-values.yaml.gotmpl
