environments:
  minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?8b22bdfea49539b010ca235fee2044a5af869cd7#tmdata/minikube
        datasets:
        - platform.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?8b22bdfea49539b010ca235fee2044a5af869cd7#tmdata/ci_simulated_stations
        datasets:
        - stations/ci-1.yaml
        - stations/ci-2.yaml
      config_files:
      - values/values-minikube.yaml
      datacentre: minikube
  aa0.5-production:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-low-deployment?f0f1478a2b5ebc240222db8ede01b94aa7f977a9#tmdata
        datasets:
        - instrument/mccs-configuration/aa0.5.yaml
        - instrument/mccs-configuration/s8-1.yaml
        - instrument/mccs-configuration/s8-6.yaml
        - instrument/mccs-configuration/s9-2.yaml
        - instrument/mccs-configuration/s10-3.yaml
      config_files:
      - values/values-aa0-5.yaml
      datacentre: infra:au-aa-mccs-cloud01-k8s
  aavs3-production:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-low-aavs3?cbbc6191a2ff3556011a55e0abf47f49ddb97936#tmdata
        datasets:
        - aavs3.yaml
      config_files: []
      # - values/values-aavs3.yaml
      datacentre: infra:au-itf-aavs302-k8s
  aavs3-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-low-aavs3?cbbc6191a2ff3556011a55e0abf47f49ddb97936#tmdata
        datasets:
        - aavs3.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - minikube.yaml
      config_files: []
      # - values/values-aavs3.yaml
      datacentre: minikube
  arcetri:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - arcetri.yaml
        - minikube.yaml
      config_files: []
      # - values/values-arcetri.yaml
      datacentre: minikube
  gmrt:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - gmrt.yaml
        - minikube.yaml
      config_files: []
      # - values/values-gmrt.yaml
      datacentre: minikube
  low-itf:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/aiv/ska-low-itf?6e443bb6ab4a1a2c0a3567990b4c3323f097f80a#tmdata
        datasets:
        - low-itf.yaml
      config_files: []
      # - values/values-low-itf.yaml
      datacentre: infra:au-itf-k8s-master01-k8s
  low-itf-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/aiv/ska-low-itf?6e443bb6ab4a1a2c0a3567990b4c3323f097f80a#tmdata
        datasets:
        - low-itf.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - minikube.yaml
      config_files: []
      # - values/values-low-itf.yaml
      datacentre: infra:au-itf-k8s-master01-k8s
  oxford:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - oxford.yaml
        - minikube.yaml
      config_files: []
      # - values/values-oxford.yaml
      datacentre: minikube
  psi-low:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-psi-low?40484382a636977c72e32a389301e17cf13fa2b5#tmdata
        datasets:
        - psi-low.yaml
      config_files: []
      # - values/values-psi-low.yaml
      datacentre: psi-low
  psi-low-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-psi-low?40484382a636977c72e32a389301e17cf13fa2b5#tmdata
        datasets:
        - psi-low.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - minikube.yaml
      config_files: []
      # - values/values-psi-low.yaml
      datacentre: psi-low
  ral:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - stfc-ral.yaml
      config_files:
      - values/values-ral.yaml
      datacentre: stfc-ral
  ral-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d080035350b5133f7ff3cbbdd8264776ca57756e#tmdata
        datasets:
        - stfc-ral.yaml
        - minikube.yaml
      config_files:
      - values/values-ral.yaml
      datacentre: stfc-ral

---

environments:
  {{.Environment.Name}}:
{{- with .Environment.Values | get "datacentre" ""}}
    kubeContext: {{.}}
{{- end}}
    values:
      - .deploy/helmfile.d/templates/tmdata.yaml.gotmpl

---

{{- $values := .Environment.Values}}
{{- range $config_file := ($values | get "config_files" list)}}
{{- $config := readFile $config_file | fromYaml}}
{{- $values = mergeOverwrite $values $config}}
{{- end}}
environments:
  {{.Environment.Name}}:
    values:
{{list $values | toYaml | indent 6}}

---

repositories: []

releases:
  - name: ska-low-mccs-daq
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-daq
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - .deploy/helmfile.d/templates/daq/daqrxs.yaml.gotmpl
      - .deploy/helmfile.d/templates/helm-values.yaml.gotmpl
