environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/minikube.yaml
      - values/values-stfc-ci.yaml
  aavs2:
    kubeContext: minikube
    values:
      - platform/aavs2.yaml
      - platform/minikube.yaml
  aavs3-deprecated:  # You should be using infra-issued credentials!
    kubeContext: aavs3-production
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=9a81412a67a852183dd39a34552df24e78a3ab83
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=9a81412a67a852183dd39a34552df24e78a3ab83
  aavs3-staging:
    kubeContext: low-itf
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=9a81412a67a852183dd39a34552df24e78a3ab83
      - values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=9a81412a67a852183dd39a34552df24e78a3ab83
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: low-itf
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=53c6326fb8d5bf65ee3575722e1cb2e14e79726a
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=53c6326fb8d5bf65ee3575722e1cb2e14e79726a
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=20895318908c03c21def95a4b0b44caa79c58b38
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=20895318908c03c21def95a4b0b44caa79c58b38
      - platform/minikube.yaml

---

repositories: []

releases:
  - name: ska-low-mccs-daq
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-daq
    version: 0.6.1
    values:
      - templates/daq.yaml.gotmpl
      - templates/helm-values.yaml.gotmpl
