environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/stfc-ci.yaml
      - values/values-stfc-ci.yaml
  aa0.5-production:
    kubeContext: infra:au-aa-mccs-cloud01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=75f85d096358140b5b56b73aad9b74dc06f84dbf
  aavs3-staging:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=75f85d096358140b5b56b73aad9b74dc06f84dbf
      - values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=75f85d096358140b5b56b73aad9b74dc06f84dbf
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=d82c9910a6286a5ec258a32366f4ce2930cee5d6
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=d82c9910a6286a5ec258a32366f4ce2930cee5d6
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=a066f45a12d373328189f390c220184cf13c1af0
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=a066f45a12d373328189f390c220184cf13c1af0
      - platform/minikube.yaml
  stfc-ral:
    values:
      - platform/stfc-ral.yaml
      - values/values-stfc-ral.yaml

---

repositories: []

releases:
  - name: ska-low-mccs-daq
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-daq
    version: 0.6.2
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - .deploy/helmfile.d/templates/daq/daqrxs.yaml.gotmpl
      - .deploy/helmfile.d/templates/helm-values.yaml.gotmpl
