environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/stfc-ci.yaml
      - values/values-stfc-ci.yaml
  aa0.5-production:
    kubeContext: infra:au-aa-mccs-cloud01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/aa0.5.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-1.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-6.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s9-2.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s10-3.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/aa0.5.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-1.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-6.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s9-2.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s10-3.yaml?ref=de56857f9fd070fd10c88e03faa511042147320e
      - values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=396d367739c6291fc27790c0cf3ea075cfd82a4b
  aavs3-staging:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=396d367739c6291fc27790c0cf3ea075cfd82a4b
      - values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=396d367739c6291fc27790c0cf3ea075cfd82a4b
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=6d9f75a8763ef794aa2d9734be8227377b0eeb86
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=6d9f75a8763ef794aa2d9734be8227377b0eeb86
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=2c9cb13ea6dd886dbc2e33b442251c85dd32376b
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=2c9cb13ea6dd886dbc2e33b442251c85dd32376b
      - platform/minikube.yaml
  stfc-ral:
    values:
      - platform/stfc-ral.yaml
      - values/values-stfc-ral.yaml
  
---

repositories: []

releases:
  - name: ska-low-mccs-daq
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-daq
    version: 0.6.1
    values:
      - templates/daq.yaml.gotmpl
      - templates/helm-values.yaml.gotmpl
