# Default values for mccs (ska-low-mccs-daq)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  sub-system:
    ska-tango-base:
      enabled: false
    taranta:
      enabled: false
    archiver:
      enabled: false
  annotations:
    app.gitlab.com/app: taranta
    app.gitlab.com/env: taranta
  minikube: false
  tango_host: databaseds-tango-base-test:10000

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3


dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.6
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    enabled: true
  tangorest:
    enabled: true

resources:
  limits:
    cpu: 60m
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 50Mi


# Default docker image - used by all of MCCS
low_mccs_daq:
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-low-mccs-daq
    tag: 0.2.0 #VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
    pullPolicy: IfNotPresent
securityContext:
  capabilities:
    add: ["NET_RAW", "IPC_LOCK", "SYS_NICE", "SYS_ADMIN", "KILL", "SYS_TIME"]


# Default ska-low-mccs-daq device server instances
deviceServers:
  daqreceiver:
    file: "data/daq-receiver.yaml"
    devices:
      - name: daqreceiver-001
        device_name: low-mccs-daq/daqreceiver/001  # mandatory
        daq_id: 1  # optional: defaults to position in this list
        receiver_interface: eth0  # optional: defaults to "eth0"
        receiver_ip: "10.0.10.150"  # mandatory
        receiver_port: 4660  # optional: defaults to 4660
        grpc_port: 50051
      - name: daqreceiver-002
        device_name: low-mccs-daq/daqreceiver/002  # mandatory
        daq_id: 2  # optional: defaults to position in this list
        receiver_interface: eth0  # optional: defaults to "eth0"
        receiver_ip: "10.0.10.151"  # mandatory
        receiver_port: 4661  # optional: defaults to 4660
        grpc_port: 50052

nodeSelector: {}

affinity: {}
