system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq

global:
  minikube: false

storage: {}
#   daq-data:
#     storage_class: nfss1  # optional but recommend; if omitted, the cluster default will be used
#     size: "250Mi"
#     labels: {}  # optional
#     annotations: {}  # optional

receivers: {}
#   1:
#     port: 50052  # optional; defaults to 50051
#     data_port: 4661  # optional; defaults to 4660
#     nvidia_gpu: true  # optional; defaults to false
#     storage: daq-data  # must refer to a PVC
#     node_selector: {}  # optional
#     affinity: {}  # optional
#     tolerations: {}  # optional
#     annotations: {}  # optional

receiver_egresses: {}
#   1:
#     ip: 10.11.12.13  # required: this is the IP address of an external DAQ receiver
#     port: 50050  # optional: defaults to 50051

image:
  registry: artefact.skao.int
  name: ska-low-mccs-daq
  tag: ~ # defaults to chart's appVersion when empty
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 12G

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
