system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

receivers: {}  # Map of specs of receivers to create
  # 1:
  #   receiver_interface: net1  # optional: defaults to "eth0"
  #   receiver_ip: ""  # empty = Determine from interface name
  #   receiver_port: 5660  # optional: defaults to 4660
  #   storage: daq-data  # must refer to a PVC: pre-existing or created above
  #   logging_level_default: 5
  #   grpc_ip: "10.0.10.151"  # optional: gRPC IP for a pre-existing DAQ
  #   grpc_port: 50051  # optional: gRPC port for a pre-existing DAQ
  #   server_node_selector: {}  # optional
  #   server_annotations: {}  # optional
  #   server_affinity: {}  # optional

storage: []  # List of specs of PVCs to create
  # - name: daq-data
  #   size: "250Mi"
  #   labels: {}  # optional
  #   annotations: {}  # optional

image:
  registry: artefact.skao.int
  name: ska-low-mccs-daq
  tag: 0.2.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 50Mi

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
