system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq

global:
  minikube: false

storage: {}  # List of specs of PVCs to create
  # daq-data:
  #   storage_class: nfss1  # optional but recommend; if omitted, the cluster default will be used
  #   size: "250Mi"
  #   labels: {}  # optional
  #   annotations: {}  # optional

receivers: {}
#   1:
#     storage: daq-data  # must refer to a PVC
#     runtime_class: nvidia # optional: must refer to a RunTimeClass existing in the cluster.
#     gpu_limit: "1" # optional
#     node_selector: {}  # optional
#     affinity: {}  # optional
#     annotations: {}  # optional

receiver_egresses: {}
#   1:
#     ip:  # required: this is the IP address of an external DAQ receiver
#     port:  # optional: defaults to 50051

# TODO: Update to 0.4.0 once released
image:
  # registry: artefact.skao.int
  registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-daq
  name: ska-low-mccs-daq
  # tag: 0.3.0
  tag: 0.3.0-dev.c4a358b7b
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 12G

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
