system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq

global:
  minikube: false

storage: []  # List of specs of PVCs to create
  # - name: daq-data
  #   size: "250Mi"
  #   labels: {}  # optional
  #   annotations: {}  # optional

# receivers:
#   1:
#     external_ip: # optional: if provided, this is the IP address of an external DAQ receiver
#     port:  # optional: defaults to 50051
#     storage: daq-data  # must refer to a PVC: pre-existing or created above
#     server_node_selector: {}  # optional
#     server_annotations: {}  # optional
#     server_affinity: {}  # optional

image:
  registry: artefact.skao.int
  name: ska-low-mccs-daq
  tag: 0.3.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 12G

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

receivers:
  1: {}