display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  sub-system:
    ska-tango-base:
      enabled: false
      enabled: false
    taranta:
      enabled: false
    archiver:
      enabled: false
  annotations:
    app.gitlab.com/app: taranta
    app.gitlab.com/env: taranta
  minikube: true
  tango_host: databaseds-tango-base-test:10000

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem


ska-taranta-dashboard:
  ingress:
    enabled: true
    nginx: true
    hostname: test-taranta.k8s.stfc.skao.int

ska-taranta-auth:
  ingress:
    enabled: true
    nginx: true
    hostname: test-taranta.k8s.stfc.skao.int

# example overrides
# ska-low-mccs:
#   deviceServers:
#     # no tiles
#     tiles:
#       instances: []
#     # change controller command
#     controller:
#       command: "SimController"
ska-low-mccs-spshw:
  facility: psi-low 
  ska-tango-base:
    enabled: false
  simulators:
    subracks:
      1:
        host: subrack-simulator-1
        
  deviceServers:
    tpms:
      instances:
        10:
          enabled: true
          simulation_config: 0 #connected to a real entity.
        13:
          enabled: true
          simulation_config: 0 #connected to a real entity.

      logging_level_default: 5
      resources:
        requests:
          memory: 512Mi

ska-low-mccs-daq:
  ska-tango-base:
    enabled: false
  low_mccs_daq:
    enabled: true
    image:
      registry: artefact.skao.int
      image: ska-low-mccs-daq
      tag: 0.2.0 #VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
      pullPolicy: IfNotPresent
  securityContext:
    capabilities:
      add: ["NET_RAW", "IPC_LOCK", "SYS_NICE", "SYS_ADMIN", "KILL", "SYS_TIME"]
  deviceServers:
    daqreceiver:
      file: "data/daq-receiver.yaml"
      devices:
        - name: daqreceiver-001
          device_name: low-mccs-daq/daqreceiver/001  # mandatory
          daq_id: 1  # optional: defaults to position in this list
          #This interface should be the 40G interface at the site of deployment.
          receiver_interface: eno33np0  # currently this has to be adjusted per site interfaces 
          receiver_ip: ""  # This can be worked out from the receiver interface
          receiver_port: 4660  # port on the receiver interface to listen for udp spead packets
          # This is the IP:PORT for the gRPC to form its TCP connection.
          grpc_ip: "10.2.2.184" 
          grpc_port: 50051
