display: ":0"
xauthority: "~/.Xauthority"

system: SW-infrastructure
subsystem: low-mccs-daq
telescope: SKA-low

labels:
  app: ska-low-mccs-daq

global:
  sub-system:
    ska-tango-base:
      enabled: false
  tango_host: databaseds-tango-base-test:10000

jupyterhub:
  hub:
    baseUrl: /jupyterhub
  ingress:
    pathType: Prefix
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  singleuser:
    image:
      name: registry.gitlab.com/ska-telescope/sdi/ska-cicd-deploy-low-itf/tango-notebook
      tag: 0.1.1
    extraEnv:
      TANGO_HOST: "databaseds-tango-base-test.ska-low-mccs-daq:10000"
  proxy:
    service:
      type: ClusterIP

ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
    hostname: "*"
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m  # 600m = 0.6 CPU
        memory: 512Mi  # 512Mi = 0.5 GB mem

ska-taranta-dashboard:
  ingress:
    enabled: true
    nginx: true
    hostname: "*"

ska-taranta-auth:
  ingress:
    enabled: true
    nginx: true
    hostname: "*"

# ska-low-mccs-daq:
#   receivers:
#     1:
#       external_ip: # optional: if provided, this is the IP address of an external DAQ receiver
#       port:  # optional: defaults to 50051
#       storage: daq-data  # must refer to a PVC: pre-existing or created above
#       server_node_selector: {}  # optional
#       server_annotations: {}  # optional
#       server_affinity: {}  # optional

# ska-low-mccs-spshw:
#   receivers:
#     1:
#       host: "daq-receiver-001"  # optional: hostname of a pre-existing DAQ
#       port: 50051  # optional: defaults to 50051
#       receiver_interface: net1  # optional: defaults to "eth0"
#       receiver_ip: ""  # empty = Determine from interface name
#       receiver_port: 5660  # optional: defaults to 4660
#       logging_level_default: 5
